---
name: continuous_integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          node-version: '3.8'
      - name: Install dependencies
        run: poetry install
      - name: Lint Python files
        run: poetry run black --check .
